server:
  port: 8080

spring:
  application:
      name: auth_system
  mvc:
    static-path-pattern: /**
    thymeleaf:
      encoding: UTF-8
      cache: false
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123126
    url: jdbc:mysql://3.145.41.4:3306/auth_system?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT&useSSL=false
mybatis-plus:
  configuration:
#    address_book table ------> AddressBook class
#    user_name attribute -----> userName attribute
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    org.apache.ibatis: DEBUG


file:
  path: C:\Users\wzh\Desktop\biyoukeji\